server:
  port: 7000
  servlet:
    session.timeout: 300

logging:
  level:
    #日志优先级（只会输出指定优先级及以上的日志信息）：trace<debug<info<warn<error
    org.springframework.web: debug
    cn.zifangsky: debug
#  file: logs/sample-websocket.log

spring:
  #Druid
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rbac_db?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&failOverReadOnly=false&useSSL=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: allcom

  #Thymeleaf
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    template-resolver-order: 0
    cache: false